![image.png](attachment:image.png)

## 🥸 Exploratory data analysis

### 🎒 Packages

In [ ]:
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_colwidth', None)

### 🚙 Utilities

In [ ]:
train_path = Path("..") / "data" / "train.csv"
# only used for final outputing (estimation on real data)
test_path = Path("..") / "data" / "test.csv"
# store
store_path = Path("..") / "data" / "store.csv"

### 📊 Data

###

In [ ]:
train = pd.read_csv(filepath_or_buffer=train_path, parse_dates=["Date"])
test = pd.read_csv(filepath_or_buffer=test_path, parse_dates=["Date"])
store = pd.read_csv(filepath_or_buffer=store_path)

/tmp/ipykernel_77268/482274471.py:1: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv(filepath_or_buffer=train_path, parse_dates=["Date"])

In [ ]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

#### Store's information

In [ ]:
store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [ ]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  datetime64[us]
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: datetime64[us](1), int64(7), object(1)
memory usage: 69.8+ MB

In [ ]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             41088 non-null  int64
 1   Store          41088 non-null  int64
 2   DayOfWeek      41088 non-null  int64
 3   Date           41088 non-null  datetime64[us]
 4   Open           41077 non-null  float64
 5   Promo          41088 non-null  int64
 6   StateHoliday   41088 non-null  str
 7   SchoolHoliday  41088 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(5), str(1)
memory usage: 2.5 MB

In [ ]:
store.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   str
 2   Assortment                 1115 non-null   str
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    str
dtypes: float64(5), int64(2), str(3)
memory usage: 87.2 KB

#### Merge store using Store as the key

In [ ]:
train_merged = train.merge(store, on="Store", how="left")
test_merged = test.merge(store, on="Store", how="left")

In [ ]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [ ]:
train_merged.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

#### Sort the data

In [ ]:
train_merged = train_merged.sort_values(["Store", "Date"])
test_merged = test_merged.sort_values(["Store", "Date"])

In [ ]:
train_merged.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
1016095,1,2,2013-01-01,0,0,0,0,a,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1014980,1,3,2013-01-02,5530,668,1,0,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1013865,1,4,2013-01-03,4327,578,1,0,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1012750,1,5,2013-01-04,4486,619,1,0,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1011635,1,6,2013-01-05,4997,635,1,0,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN

---

### 💩 Simple data cleaning, one file prototype

Customers
Number of customers that day
⚠️ Important:
Highly correlated with sales
BUT NOT available in test set
So you cannot use it as a feature in real prediction

👉 Think of it as “training-only insight”

Assortment
Product variety:
a = basic
b = extra
c = extended (largest variety)

Meaning:

More assortment → usually higher sales

CompetitionDistance
Distance to nearest competitor store (meters)

Meaning:

Closer competitor → usually lower sales

CompetitionOpenSinceMonth/Year
When competitor opened nearby

Meaning:

Helps model “competition pressure over time”

---

❌ Pitfall 1: Using closed stores

If Open = 0:

Sales = 0 always
But this is NOT real demand

👉 If you train on this:

Model learns “closed = zero sales”
This corrupts learning

❌ Pitfall 2: Using Customers in features
Customers strongly correlates with Sales
BUT NOT in test set

👉 If used:

your model becomes invalid for prediction

❌ Pitfall 3: Missing values are NOT random

For example:

Competition data missing ≠ error

It often means:

“no competitor nearby / unknown timing”

So naive filling can distort signal.

❌ Pitfall 4: Date leakage in feature engineering later

Even cleaning must prepare for:

time-based splits
correct sorting

In [ ]:
train_merged = train_merged[train_merged["Open"] == 1]

Why this is safe:

Because:

test set only includes open predictions implicitly
closed days are not meaningful demand signals

In [ ]:
train_merged = train_merged[train_merged["Sales"] > 0]

Why?
RMSPE ignores 0 sales anyway
zero sales often = closed or errors

#### Fix data type

Why?

Without this:

model treats categories as numbers
introduces fake ordering (0 < a < b < c)

In [ ]:
train_merged["StateHoliday"] = train_merged["StateHoliday"].astype(str)
test_merged["StateHoliday"] = test_merged["StateHoliday"].astype(str)

#### Competition distance

In [ ]:
median_dist = train_merged["CompetitionDistance"].median()

train_merged["CompetitionDistance"] = train_merged["CompetitionDistance"].fillna(median_dist)
test_merged["CompetitionDistance"] = test_merged["CompetitionDistance"].fillna(median_dist)

#### COmptetion start date

In [ ]:
for col in ["CompetitionOpenSinceMonth", "CompetitionOpenSinceYear"]:
    train_merged[col] = train_merged[col].fillna(0)
    test_merged[col] = test_merged[col].fillna(0)

#### Promt2 field

In [ ]:
for col in ["Promo2SinceWeek", "Promo2SinceYear", "PromoInterval"]:
    train_merged[col] = train_merged[col].fillna(0)
    test_merged[col] = test_merged[col].fillna(0)

#### Remove leakage column

In [ ]:
train = train.drop(columns=["Customers"])

#### - Srorting

In [ ]:
train_merged = train_merged.sort_values(["Store", "Date"])
test_merged = test_merged.sort_values(["Store", "Date"])

#### CHecking for data consisistency

In [ ]:
print(train_merged.isnull().sum().sort_values(ascending=False).head(10))

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
StoreType        0
dtype: int64

In [ ]:
print(train_merged["Store"].nunique(), test_merged["Store"].nunique())

1115 856

Raw Data
   ↓
(1) Light EDA  ← initial understanding (VERY IMPORTANT)
   ↓
(2) Light cleaning (fix obvious issues)
   ↓
(3) Deeper EDA ← now data is more reliable
   ↓
(4) Feature engineering
   ↓
(5) Modeling
   ↓
(6) Error analysis → more EDA again

🧭 A. BEFORE cleaning (Exploratory understanding)

You try to answer:

What does each column mean?
What is missing?
Are there weird values?
What is the target distribution?
Are there duplicates / broken rows?

👉 This is “diagnostic EDA”

🧹 B. DURING cleaning (decision-making EDA)

You use EDA to decide:

Should I remove Open = 0?
Should I drop outliers?
How should I impute missing values?
Is this feature skewed?

👉 This is “action EDA”

🚀 C. AFTER cleaning (modeling EDA)

Now you analyze:

Correlation with target
Seasonality patterns
Store-level behavior
Promo effects

👉 This is “feature engineering EDA”